version: '3'

services:
  database-mysql:
    container_name: database-mysql
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_PASSWORD: 'simple'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'simple'
      TZ: Asia/Seoul

    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

    ports:
      - '13306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  application-chat:
    container_name: service-chat
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'

networks:
  default:
